package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginView extends JFrame {

    private CtrlPresentation ctrlPresentation;

    private JButton loginButton;
    private JButton newPlayerButton;
    private JTextField loginText;
    private JButton exitButton;
    private JPanel panel;
    private JLabel loginLabel;


    private void initializeComponents() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        loginButton.setText("Login");
        newPlayerButton.setText("New Player");
        setContentPane(panel);
        setSize(300, 150);
        //This function makes the window appear in the middle of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                loginButtonPress(event);
            }
        });

        newPlayerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                newPlayerButtonPressed(event);
            }
        });

        exitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                exitButtonPress(event);
            }
        });

        loginLabel.setText("Enter a previously created User");

    }

    public LoginView(CtrlPresentation ctrlPresentation) {
        this.ctrlPresentation = ctrlPresentation;
        initializeComponents();
        setVisible(true);
    }

    public void exitButtonPress(ActionEvent event) {
        System.exit(0);
    }

    public void loginButtonPress(ActionEvent event) {
        String userID = loginText.getText();
        ctrlPresentation.loginUser(userID);
    }

    public void newPlayerButtonPressed(ActionEvent event) {
        setVisible(false);
        ctrlPresentation.loadUserView();
    }

    public void notExistingUser() {
        setVisible(true);
        JOptionPane.showMessageDialog(this, "The username doesn't Exists, use a different username");
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        loginButton = new JButton();
        loginButton.setBackground(new Color(-13991628));
        loginButton.setText("Log In");
        panel.add(loginButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        exitButton = new JButton();
        exitButton.setBackground(new Color(-4716793));
        exitButton.setText("Exit");
        panel.add(exitButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        newPlayerButton = new JButton();
        newPlayerButton.setText("Create user");
        panel.add(newPlayerButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel.add(spacer2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        loginText = new JTextField();
        panel.add(loginText, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginLabel = new JLabel();
        loginLabel.setText("Label");
        panel.add(loginLabel, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
